import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

export default function Terms() {
  return (
    <div className="legal-page">
      <Navbar />
      <div className="container" style={{ paddingTop: '120px', paddingBottom: '80px', maxWidth: '800px' }}>
        <h1 style={{ fontSize: '3rem', marginBottom: '2rem', fontWeight: 800 }}>Terms of Service</h1>
        <p className="text-secondary" style={{ marginBottom: '2rem' }}>Last updated: April 13, 2026</p>
        
        <section style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem', fontWeight: 700 }}>1. Agreement to Terms</h2>
          <p style={{ lineHeight: 1.7, marginBottom: '1rem' }}>
            By accessing or using StudyMind AI, you agree to be bound by these Terms of Service. If you disagree 
            with any part of the terms, you may not access the service.
          </p>
        </section>

        <section style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem', fontWeight: 700 }}>2. AI Content Disclaimer</h2>
          <p style={{ lineHeight: 1.7, marginBottom: '1rem' }}>
            StudyMind AI provides content generated by artificial intelligence. While we strive for accuracy, 
            AI-generated content can occasionally be incorrect or biased. You are responsible for verifying 
            the information provided before use.
          </p>
        </section>

        <section style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem', fontWeight: 700 }}>3. User Conduct</h2>
          <p style={{ lineHeight: 1.7, marginBottom: '1rem' }}>
            You agree not to use the service for any illegal or unauthorized purpose. You must not use the AI 
            to generate harmful, deceptive, or malicious content.
          </p>
        </section>

        <section style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem', fontWeight: 700 }}>4. Subscription & Payments</h2>
          <p style={{ lineHeight: 1.7, marginBottom: '1rem' }}>
            The Pro plan is a monthly subscription. Payments are processed via Razorpay. You can cancel 
            your subscription at any time, but we do not offer refunds for partial billing cycles.
          </p>
        </section>

        <section style={{ marginBottom: '2.5rem' }}>
          <h2 style={{ fontSize: '1.5rem', marginBottom: '1rem', fontWeight: 700 }}>5. Limitation of Liability</h2>
          <p style={{ lineHeight: 1.7, marginBottom: '1rem' }}>
            StudyMind AI shall not be liable for any indirect, incidental, special, or consequential damages 
            resulting from the use or inability to use the service.
          </p>
        </section>
      </div>
      <Footer />
    </div>
  );
}
